Disable embodiment/Learning/main as it doesn't compile and is unused
And will very likely remain unused in the future.

The error in question is

/usr/bin/ld: CMakeFiles/interactive-hillclimbing.dir/interactive-hillclimbing.cc.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'
//usr/lib/x86_64-linux-gnu/libboost_system.so.1.54.0: error adding symbols: DSO missing from command line

I still don't understand what is causing that.